### ISSUE TITLE
jquery method .on() does not work in drupal 7

### ISSUE THREAD

**Issue by dheeraj-br** [chriscook/first-visit-popup#3]
i was using your plugin for my work in drupal 7, and it worked fine as a standalone, when i integrated it with my page.tpl.php (base page in drupal talk) it did't work as expected, the function was called on page load and did't wait untill click event. i had to replace .on() with .click() to make it work! jquery version is 1.7.  it supports this. 

the problem could be that .on() has one single handler for all its selectors and .click() has multiple handlers. 

what's your opinion on this, am i doing it wrong?

**Comment by chriscook** [comment]
Hi, I've not used Drupal myself so I'm not sure how it would affect the plugin, I suppose it's probably another script interfering with this one in some way.

Which line is it you had to change?

**Comment by dheeraj-br** [comment]
Thanks for the reply, its line 58 of the jquery.firstVisitPopup.js [link](https://github.com/chriscook/first-visit-popup/blob/master/jquery.firstVisitPopup.js#L58)

i will do a fresh installation of drupal just to test this one out, and let you know. thanks!
