### ISSUE TITLE
Setting cookie to a different value

### ISSUE THREAD

**Issue by brobinson1283** [chriscook/first-visit-popup#4]
I need to change the cookie length. I dont want it to set to only one visit. Id like to set it to something like a cookie length of one day. So if the user comes back the following day they will see it again. Thoughts?

**Comment by chriscook** [comment]
Hi, although I've not built this in as an option yet, it's easy enough to manually change. On line 18, change `31536000000` (milliseconds in a year) to `86400000` (milliseconds in a day).
